# Generated by Django 3.2.2 on 2022-08-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('length', models.TimeField(blank=True, default='')),
                ('track_number', models.PositiveSmallIntegerField(blank=True, default='', max_length=3)),
                ('disc_number', models.PositiveSmallIntegerField(blank=True, default='', max_length=3)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.albums')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
