# Generated by Django 3.2.2 on 2022-08-05 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_albums_album'),
        ('artists', '0001_initial'),
        ('songs', '0002_auto_20220803_2159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
