# Generated by Django 3.2.2 on 2022-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_rename_songs_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='disc_number',
            field=models.PositiveSmallIntegerField(blank=True, default='0'),
        ),
        migrations.AlterField(
            model_name='song',
            name='length',
            field=models.TimeField(blank=True, default='0:00'),
        ),
        migrations.AlterField(
            model_name='song',
            name='track_number',
            field=models.PositiveSmallIntegerField(blank=True, default='0'),
        ),
    ]
