# Generated by Django 3.2.2 on 2022-08-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_remove_song_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
