# Generated by Django 3.2.2 on 2022-08-30 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0003_artist'),
        ('albums', '0006_album'),
        ('songs', '0006_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('track_number', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('disc_number', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
