# Generated by Django 3.2.2 on 2022-09-01 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='length',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
