# Generated by Django 3.2.2 on 2022-08-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_delete_album'),
        ('songs', '0006_delete_song'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
