# Generated by Django 3.2.2 on 2022-08-04 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('year_released', models.PositiveSmallIntegerField(default='', max_length=4)),
                ('track_count', models.PositiveSmallIntegerField(blank=True, default='', max_length=3, verbose_name='Total Number of Tracks')),
                ('disc_count', models.PositiveSmallIntegerField(blank=True, default='', max_length=3, verbose_name='Total Number of Discs')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
            ],
        ),
    ]
