# Generated by Django 3.2.2 on 2022-08-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='disc_count',
            field=models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Total Number of Discs'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='track_count',
            field=models.PositiveSmallIntegerField(blank=True, default='', verbose_name='Total Number of Tracks'),
        ),
        migrations.AlterField(
            model_name='albums',
            name='year_released',
            field=models.PositiveSmallIntegerField(default=''),
        ),
    ]
