# Generated by Django 3.2.2 on 2022-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_rename_albums_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='disc_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Total Number of Discs'),
        ),
        migrations.AlterField(
            model_name='album',
            name='track_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Total Number of Tracks'),
        ),
        migrations.AlterField(
            model_name='album',
            name='year_released',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
