# Generated by Django 3.2.2 on 2022-08-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_delete_song'),
        ('albums', '0004_auto_20220807_0723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
    ]
